version: '3.9'

services:
  test_site:
    image: nginx:stable-alpine
    volumes:
      - ./crawler/tests/fixtures/site:/usr/share/nginx/html
      - ./crawler/tests/fixtures/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  crawler:
    build: .
    volumes:
      - ./crawler:/crawler
    network_mode: host
    command: tail -f /dev/null
